#!/usr/bin/env python3
"""
Fix all translation files — add missing keys and translate untranslated values.
Uses built-in translation dictionaries instead of API calls for reliability.
"""
import json
import os
import copy

MESSAGES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'apps', 'web', 'messages')

def load_json(lang):
    with open(os.path.join(MESSAGES_DIR, f'{lang}.json'), 'r', encoding='utf-8') as f:
        return json.load(f)

def save_json(lang, data):
    with open(os.path.join(MESSAGES_DIR, f'{lang}.json'), 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write('\n')

def get_value(obj, key_path):
    keys = key_path.split('.')
    cur = obj
    for k in keys:
        cur = cur[k]
    return cur

def set_value(obj, key_path, value):
    keys = key_path.split('.')
    cur = obj
    for k in keys[:-1]:
        if k not in cur:
            cur[k] = {}
        cur = cur[k]
    cur[keys[-1]] = value

def has_key(obj, key_path):
    keys = key_path.split('.')
    cur = obj
    for k in keys:
        if k not in cur:
            return False
        cur = cur[k]
    return True

# ============================================================
# TRANSLATION DICTIONARIES
# Key = English text, Value = dict of {lang_code: translation}
# ============================================================

# Common UI terms
COMMON = {
    # agentStore
    "Activating agent...": {"ar":"جارٍ تفعيل الوكيل...","bn":"এজেন্ট সক্রিয় করা হচ্ছে...","cs":"Aktivace agenta...","da":"Aktiverer agent...","de":"Agent wird aktiviert...","es":"Activando agente...","fa":"در حال فعال‌سازی عامل...","fi":"Aktivoidaan agenttia...","fil":"Ina-activate ang agent...","fr":"Activation de l'agent...","he":"מפעיל סוכן...","hi":"एजेंट सक्रिय किया जा रहा है...","hu":"Ügynök aktiválása...","id":"Mengaktifkan agen...","it":"Attivazione agente...","ja":"エージェントを起動中...","ko":"에이전트 활성화 중...","ms":"Mengaktifkan ejen...","nl":"Agent activeren...","no":"Aktiverer agent...","pl":"Aktywowanie agenta...","pt":"Ativando agente...","ro":"Se activează agentul...","ru":"Активация агента...","sv":"Aktiverar agent...","th":"กำลังเปิดใช้งานเอเจนต์...","tr":"Ajan etkinleştiriliyor...","uk":"Активація агента...","ur":"ایجنٹ فعال ہو رہا ہے...","vi":"Đang kích hoạt agent...","zh":"正在激活代理..."},
    "Trading agent activated successfully": {"ar":"تم تفعيل وكيل التداول بنجاح","bn":"ট্রেডিং এজেন্ট সফলভাবে সক্রিয় হয়েছে","cs":"Obchodní agent byl úspěšně aktivován","da":"Handelsagent aktiveret","de":"Handelsagent erfolgreich aktiviert","es":"Agente de trading activado","fa":"عامل معاملاتی با موفقیت فعال شد","fi":"Kaupankäyntiagentti aktivoitu","fil":"Matagumpay na na-activate ang trading agent","fr":"Agent de trading activé","he":"סוכן מסחר הופעל בהצלחה","hi":"ट्रेडिंग एजेंट सफलतापूर्वक सक्रिय","hu":"Kereskedési ügynök sikeresen aktiválva","id":"Agen perdagangan berhasil diaktifkan","it":"Agente di trading attivato","ja":"トレーディングエージェントが起動しました","ko":"트레이딩 에이전트가 활성화되었습니다","ms":"Ejen dagang berjaya diaktifkan","nl":"Handelsagent geactiveerd","no":"Handelsagent aktivert","pl":"Agent handlowy aktywowany","pt":"Agente de trading ativado","ro":"Agentul de tranzacționare activat","ru":"Торговый агент активирован","sv":"Handelsagent aktiverad","th":"เปิดใช้งานเอเจนต์การเทรดสำเร็จ","tr":"İşlem aracısı etkinleştirildi","uk":"Торговий агент активовано","ur":"ٹریڈنگ ایجنٹ کامیابی سے فعال ہو گیا","vi":"Agent giao dịch đã được kích hoạt","zh":"交易代理已成功激活"},
    "Auto (Adaptive)": {"ar":"تلقائي (متكيف)","bn":"স্বয়ংক্রিয় (অভিযোজনমূলক)","cs":"Automatický (Adaptivní)","da":"Auto (Tilpassende)","de":"Auto (Adaptiv)","es":"Auto (Adaptativo)","fa":"خودکار (تطبیقی)","fi":"Auto (Mukautuva)","fil":"Auto (Adaptive)","fr":"Auto (Adaptatif)","he":"אוטומטי (אדפטיבי)","hi":"स्वचालित (अनुकूलनीय)","hu":"Auto (Adaptív)","id":"Otomatis (Adaptif)","it":"Auto (Adattivo)","ja":"自動（アダプティブ）","ko":"자동 (적응형)","ms":"Auto (Adaptif)","nl":"Auto (Adaptief)","no":"Auto (Tilpassende)","pl":"Auto (Adaptacyjny)","pt":"Auto (Adaptativo)","ro":"Auto (Adaptiv)","ru":"Авто (Адаптивный)","sv":"Auto (Anpassningsbar)","th":"อัตโนมัติ (ปรับตัว)","tr":"Otomatik (Uyarlanır)","uk":"Авто (Адаптивний)","ur":"خودکار (آڈاپٹو)","vi":"Tự động (Thích nghi)","zh":"自动（自适应）"},
    "Momentum Breakout": {"ar":"اختراق الزخم","bn":"মোমেন্টাম ব্রেকআউট","cs":"Průlom momentumu","da":"Momentum gennembrud","de":"Momentum-Ausbruch","es":"Ruptura de momentum","fa":"شکست مومنتوم","fi":"Momentumin läpimurto","fil":"Momentum Breakout","fr":"Rupture d'élan","he":"פריצת מומנטום","hi":"मोमेंटम ब्रेकआउट","hu":"Momentum áttörés","id":"Terobosan Momentum","it":"Rottura momentum","ja":"モメンタムブレイクアウト","ko":"모멘텀 돌파","ms":"Pecahan Momentum","nl":"Momentum doorbraak","no":"Momentum-gjennombrudd","pl":"Wybicie momentum","pt":"Ruptura de momentum","ro":"Ruptură de momentum","ru":"Прорыв импульса","sv":"Momentum-genombrott","th":"ทะลุโมเมนตัม","tr":"Momentum Kırılımı","uk":"Прорив імпульсу","ur":"مومینٹم بریک آؤٹ","vi":"Đột phá động lượng","zh":"动量突破"},
    "Grid": {"ar":"شبكة","bn":"গ্রিড","cs":"Mřížka","da":"Grid","de":"Grid","es":"Grid","fa":"گرید","fi":"Grid","fil":"Grid","fr":"Grille","he":"גריד","hi":"ग्रिड","hu":"Rács","id":"Grid","it":"Griglia","ja":"グリッド","ko":"그리드","ms":"Grid","nl":"Grid","no":"Grid","pl":"Siatka","pt":"Grade","ro":"Grid","ru":"Сетка","sv":"Grid","th":"กริด","tr":"Grid","uk":"Сітка","ur":"گرڈ","vi":"Lưới","zh":"网格"},
    "Mean Reversion": {"ar":"عودة للمتوسط","bn":"মিন রিভার্সন","cs":"Návrat k průměru","da":"Middelværdireversion","de":"Mean Reversion","es":"Reversión a la media","fa":"بازگشت به میانگین","fi":"Keskiverton paluu","fil":"Mean Reversion","fr":"Retour à la moyenne","he":"חזרה לממוצע","hi":"मीन रिवर्शन","hu":"Átlaghoz való visszatérés","id":"Mean Reversion","it":"Ritorno alla media","ja":"平均回帰","ko":"평균 회귀","ms":"Pembalikan Min","nl":"Mean Reversion","no":"Gjennomsnittsreversjon","pl":"Powrót do średniej","pt":"Reversão à média","ro":"Reversie la medie","ru":"Возврат к среднему","sv":"Mean Reversion","th":"กลับสู่ค่าเฉลี่ย","tr":"Ortalama Dönüş","uk":"Повернення до середнього","ur":"مین ریورژن","vi":"Hoàn về trung bình","zh":"均值回归"},
    "Scalping": {"ar":"سكالبينج","bn":"স্কাল্পিং","cs":"Scalping","da":"Scalping","de":"Scalping","es":"Scalping","fa":"اسکالپینگ","fi":"Scalping","fil":"Scalping","fr":"Scalping","he":"סקלפינג","hi":"स्काल्पिंग","hu":"Scalping","id":"Scalping","it":"Scalping","ja":"スキャルピング","ko":"스캘핑","ms":"Scalping","nl":"Scalping","no":"Scalping","pl":"Scalping","pt":"Scalping","ro":"Scalping","ru":"Скальпинг","sv":"Scalping","th":"สเกลปิ้ง","tr":"Scalping","uk":"Скальпінг","ur":"اسکیلپنگ","vi":"Scalping","zh":"剥头皮"},
    "Swing": {"ar":"سوينج","bn":"সুইং","cs":"Swing","da":"Swing","de":"Swing","es":"Swing","fa":"سوئینگ","fi":"Swing","fil":"Swing","fr":"Swing","he":"סווינג","hi":"स्विंग","hu":"Swing","id":"Swing","it":"Swing","ja":"スイング","ko":"스윙","ms":"Swing","nl":"Swing","no":"Swing","pl":"Swing","pt":"Swing","ro":"Swing","ru":"Свинг","sv":"Swing","th":"สวิง","tr":"Swing","uk":"Свінг","ur":"سوئنگ","vi":"Swing","zh":"波段"},
    "Trade — Daily Profit": {"ar":"تداول — الربح اليومي","bn":"ট্রেড — দৈনিক লাভ","cs":"Obchod — Denní zisk","da":"Handel — Daglig profit","de":"Handel — Tagesgewinn","es":"Trade — Beneficio diario","fa":"معامله — سود روزانه","fi":"Kauppa — Päivävoitto","fil":"Trade — Arawang Kita","fr":"Trade — Profit quotidien","he":"מסחר — רווח יומי","hi":"ट्रेड — दैनिक लाभ","hu":"Kereskedelem — Napi profit","id":"Perdagangan — Keuntungan Harian","it":"Trade — Profitto giornaliero","ja":"トレード — 日次利益","ko":"트레이드 — 일일 수익","ms":"Dagangan — Keuntungan Harian","nl":"Handel — Dagelijkse winst","no":"Handel — Daglig profitt","pl":"Handel — Dzienny zysk","pt":"Trade — Lucro diário","ro":"Tranzacție — Profit zilnic","ru":"Торговля — Дневная прибыль","sv":"Handel — Daglig vinst","th":"เทรด — กำไรรายวัน","tr":"İşlem — Günlük Kâr","uk":"Торгівля — Щоденний прибуток","ur":"ٹریڈ — روزانہ منافع","vi":"Giao dịch — Lợi nhuận hàng ngày","zh":"交易 — 每日盈利"},
    "Trading service unavailable": {"ar":"خدمة التداول غير متاحة","bn":"ট্রেডিং সার্ভিস অনুপলব্ধ","cs":"Obchodní služba nedostupná","da":"Handelstjeneste utilgængelig","de":"Handelsservice nicht verfügbar","es":"Servicio de trading no disponible","fa":"سرویس معاملاتی در دسترس نیست","fi":"Kaupankäyntipalvelu ei käytettävissä","fil":"Hindi available ang trading service","fr":"Service de trading indisponible","he":"שירות מסחר אינו זמין","hi":"ट्रेडिंग सेवा अनुपलब्ध","hu":"Kereskedési szolgáltatás nem elérhető","id":"Layanan perdagangan tidak tersedia","it":"Servizio di trading non disponibile","ja":"取引サービスは利用できません","ko":"트레이딩 서비스를 사용할 수 없습니다","ms":"Perkhidmatan dagangan tidak tersedia","nl":"Handelsservice niet beschikbaar","no":"Handelstjeneste utilgjengelig","pl":"Usługa handlowa niedostępna","pt":"Serviço de trading indisponível","ro":"Serviciu de tranzacționare indisponibil","ru":"Торговый сервис недоступен","sv":"Handelstjänst otillgänglig","th":"บริการเทรดไม่พร้อมใช้งาน","tr":"İşlem servisi kullanılamıyor","uk":"Торговий сервіс недоступний","ur":"ٹریڈنگ سروس دستیاب نہیں","vi":"Dịch vụ giao dịch không khả dụng","zh":"交易服务不可用"},
    
    # ai section
    "Live": {"ar":"مباشر","bn":"লাইভ","cs":"Živě","da":"Live","de":"Live","es":"En vivo","fa":"زنده","fi":"Live","fil":"Live","fr":"En direct","he":"חי","hi":"लाइव","hu":"Élő","id":"Langsung","it":"Live","ja":"ライブ","ko":"라이브","ms":"Langsung","nl":"Live","no":"Live","pl":"Na żywo","pt":"Ao vivo","ro":"Live","ru":"В эфире","sv":"Live","th":"สด","tr":"Canlı","uk":"Наживо","ur":"لائیو","vi":"Trực tiếp","zh":"实时"},
    "Cached AI analysis — still valid": {"ar":"تحليل AI مخزّن — لا يزال صالحاً","bn":"ক্যাশড AI বিশ্লেষণ — এখনও বৈধ","cs":"Uložená AI analýza — stále platná","da":"Cachelagret AI-analyse — stadig gyldig","de":"Zwischengespeicherte KI-Analyse — noch gültig","es":"Análisis de IA en caché — aún válido","fa":"تحلیل AI کش شده — همچنان معتبر","fi":"Välimuistissa oleva AI-analyysi — yhä voimassa","fil":"Naka-cache na AI analysis — still valid","fr":"Analyse IA en cache — toujours valide","he":"ניתוח AI מטמון — עדיין תקף","hi":"कैश किया गया AI विश्लेषण — अभी भी मान्य","hu":"Gyorsítótárazott AI elemzés — még érvényes","id":"Analisis AI di-cache — masih valid","it":"Analisi IA nella cache — ancora valida","ja":"キャッシュされたAI分析 — まだ有効","ko":"캐시된 AI 분석 — 여전히 유효","ms":"Analisis AI cache — masih sah","nl":"Gecachte AI-analyse — nog geldig","no":"Hurtigbufret AI-analyse — fortsatt gyldig","pl":"Analiza AI z pamięci podręcznej — nadal ważna","pt":"Análise de IA em cache — ainda válida","ro":"Analiză AI din cache — încă validă","ru":"Кэшированный AI-анализ — всё ещё актуален","sv":"Cachad AI-analys — fortfarande giltig","th":"AI วิเคราะห์จากแคช — ยังใช้ได้","tr":"Önbelleğe alınmış AI analizi — hâlâ geçerli","uk":"Кешований AI-аналіз — досі актуальний","ur":"کیشڈ AI تجزیہ — اب بھی درست","vi":"Phân tích AI đã lưu — vẫn còn hiệu lực","zh":"缓存的AI分析 — 仍然有效"},
    "Failed to get consensus": {"ar":"فشل الحصول على الإجماع","bn":"কনসেনসাস পেতে ব্যর্থ","cs":"Nepodařilo se získat konsenzus","da":"Kunne ikke opnå konsensus","de":"Konsens konnte nicht erreicht werden","es":"No se pudo obtener el consenso","fa":"دریافت اجماع ناموفق بود","fi":"Yhteisymmärrystä ei saavutettu","fil":"Hindi nakuha ang consensus","fr":"Impossible d'obtenir le consensus","he":"לא ניתן להשיג קונצנזוס","hi":"सहमति प्राप्त करने में विफल","hu":"Nem sikerült konszenzust elérni","id":"Gagal mendapatkan konsensus","it":"Impossibile ottenere il consenso","ja":"コンセンサスの取得に失敗","ko":"합의 획득 실패","ms":"Gagal mendapatkan konsensus","nl":"Consensus niet bereikt","no":"Kunne ikke oppnå konsensus","pl":"Nie udało się uzyskać konsensusu","pt":"Falha ao obter consenso","ro":"Nu s-a obținut consensul","ru":"Не удалось достичь консенсуса","sv":"Kunde inte uppnå konsensus","th":"ไม่สามารถได้มาซึ่งฉันทามติ","tr":"Mutabakat alınamadı","uk":"Не вдалося досягти консенсусу","ur":"консенсус حاصل کرنے میں ناکام","vi":"Không thể đạt được đồng thuận","zh":"获取共识失败"},
    "AI Insights": {"ar":"رؤى AI","bn":"AI ইনসাইট","cs":"AI poznatky","da":"AI-indsigt","de":"KI-Einblicke","es":"Perspectivas de IA","fa":"بینش AI","fi":"AI-näkemykset","fil":"AI Insights","fr":"Perspectives IA","he":"תובנות AI","hi":"AI अंतर्दृष्टि","hu":"AI meglátások","id":"Wawasan AI","it":"Approfondimenti IA","ja":"AIインサイト","ko":"AI 인사이트","ms":"Pandangan AI","nl":"AI-inzichten","no":"AI-innsikt","pl":"Spostrzeżenia AI","pt":"Insights de IA","ro":"Informații AI","ru":"Инсайты AI","sv":"AI-insikter","th":"AI Insights","tr":"AI Öngörüleri","uk":"Інсайти AI","ur":"AI بصائر","vi":"Thông tin AI","zh":"AI洞察"},
    "Alert": {"ar":"تنبيه","bn":"সতর্কতা","cs":"Upozornění","da":"Advarsel","de":"Warnung","es":"Alerta","fa":"هشدار","fi":"Hälytys","fil":"Alerto","fr":"Alerte","he":"התראה","hi":"अलर्ट","hu":"Riasztás","id":"Peringatan","it":"Avviso","ja":"アラート","ko":"알림","ms":"Amaran","nl":"Waarschuwing","no":"Varsel","pl":"Alert","pt":"Alerta","ro":"Alertă","ru":"Оповещение","sv":"Varning","th":"แจ้งเตือน","tr":"Uyarı","uk":"Сповіщення","ur":"الرٹ","vi":"Cảnh báo","zh":"警报"},
    "Bearish": {"ar":"هابط","bn":"বিয়ারিশ","cs":"Medvědí","da":"Bearish","de":"Bärisch","es":"Bajista","fa":"نزولی","fi":"Laskava","fil":"Bearish","fr":"Baissier","he":"דובי","hi":"मंदी","hu":"Medve","id":"Bearish","it":"Ribassista","ja":"弱気","ko":"약세","ms":"Bearish","nl":"Bearish","no":"Bearish","pl":"Spadkowy","pt":"Baixista","ro":"Bearish","ru":"Медвежий","sv":"Bearish","th":"ขาลง","tr":"Düşüş","uk":"Ведмежий","ur":"بیئرش","vi":"Giảm","zh":"看跌"},
    "Bullish": {"ar":"صاعد","bn":"বুলিশ","cs":"Býčí","da":"Bullish","de":"Bullisch","es":"Alcista","fa":"صعودی","fi":"Nouseva","fil":"Bullish","fr":"Haussier","he":"שורי","hi":"तेजी","hu":"Bika","id":"Bullish","it":"Rialzista","ja":"強気","ko":"강세","ms":"Bullish","nl":"Bullish","no":"Bullish","pl":"Wzrostowy","pt":"Altista","ro":"Bullish","ru":"Бычий","sv":"Bullish","th":"ขาขึ้น","tr":"Yükseliş","uk":"Бичачий","ur":"بلش","vi":"Tăng","zh":"看涨"},
    "Neutral": {"ar":"محايد","bn":"নিরপেক্ষ","cs":"Neutrální","da":"Neutral","de":"Neutral","es":"Neutral","fa":"خنثی","fi":"Neutraali","fil":"Neutral","fr":"Neutre","he":"נייטרלי","hi":"तटस्थ","hu":"Semleges","id":"Netral","it":"Neutro","ja":"ニュートラル","ko":"중립","ms":"Neutral","nl":"Neutraal","no":"Nøytral","pl":"Neutralny","pt":"Neutro","ro":"Neutru","ru":"Нейтральный","sv":"Neutral","th":"กลาง","tr":"Nötr","uk":"Нейтральний","ur":"غیر جانبدار","vi":"Trung tính","zh":"中性"},
    "Medium": {"ar":"متوسط","bn":"মাঝারি","cs":"Střední","da":"Medium","de":"Mittel","es":"Medio","fa":"متوسط","fi":"Keskitaso","fil":"Katamtaman","fr":"Moyen","he":"בינוני","hi":"मध्यम","hu":"Közepes","id":"Sedang","it":"Medio","ja":"ミディアム","ko":"중간","ms":"Sederhana","nl":"Gemiddeld","no":"Middels","pl":"Średni","pt":"Médio","ro":"Mediu","ru":"Средний","sv":"Medel","th":"ปานกลาง","tr":"Orta","uk":"Середній","ur":"درمیانہ","vi":"Trung bình","zh":"中等"},
    "Volatile": {"ar":"متقلب","bn":"অস্থির","cs":"Volatile","da":"Volatile","de":"Volatil","es":"Volátil","fa":"نوسانی","fi":"Volatiili","fil":"Volatile","fr":"Volatil","he":"תנודתי","hi":"अस्थिर","hu":"Volatilis","id":"Volatile","it":"Volatile","ja":"ボラタイル","ko":"변동성","ms":"Volatile","nl":"Volatiel","no":"Volatile","pl":"Zmienny","pt":"Volátil","ro":"Volatile","ru":"Волатильный","sv":"Volatil","th":"ผันผวน","tr":"Oynak","uk":"Волатильний","ur":"وولیٹائل","vi":"Biến động","zh":"波动"},
    "Risk": {"ar":"مخاطرة","bn":"ঝুঁকি","cs":"Riziko","da":"Risiko","de":"Risiko","es":"Riesgo","fa":"ریسک","fi":"Riski","fil":"Panganib","fr":"Risque","he":"סיכון","hi":"जोखिम","hu":"Kockázat","id":"Risiko","it":"Rischio","ja":"リスク","ko":"위험","ms":"Risiko","nl":"Risico","no":"Risiko","pl":"Ryzyko","pt":"Risco","ro":"Risc","ru":"Риск","sv":"Risk","th":"ความเสี่ยง","tr":"Risk","uk":"Ризик","ur":"خطرہ","vi":"Rủi ro","zh":"风险"},
    "Sentiment": {"ar":"المشاعر","bn":"সেন্টিমেন্ট","cs":"Sentiment","da":"Sentiment","de":"Stimmung","es":"Sentimiento","fa":"احساسات بازار","fi":"Markkinasentimentti","fil":"Sentimento","fr":"Sentiment","he":"סנטימנט","hi":"भावना","hu":"Hangulat","id":"Sentimen","it":"Sentimento","ja":"センチメント","ko":"심리","ms":"Sentimen","nl":"Sentiment","no":"Sentiment","pl":"Sentyment","pt":"Sentimento","ro":"Sentiment","ru":"Настроение","sv":"Sentiment","th":"ความรู้สึกตลาด","tr":"Duygu","uk":"Настрій","ur":"سمجھا","vi":"Tâm lý","zh":"情绪"},
    "Sharp Volatility": {"ar":"تقلب حاد","bn":"তীব্র অস্থিরতা","cs":"Ostrá volatilita","da":"Skarp volatilitet","de":"Starke Volatilität","es":"Volatilidad aguda","fa":"نوسان شدید","fi":"Terävä volatiliteetti","fil":"Matinding Volatility","fr":"Forte volatilité","he":"תנודתיות חדה","hi":"तीव्र अस्थिरता","hu":"Éles volatilitás","id":"Volatilitas Tajam","it":"Forte volatilità","ja":"急激なボラティリティ","ko":"급격한 변동성","ms":"Volatiliti Tajam","nl":"Scherpe volatiliteit","no":"Skarp volatilitet","pl":"Ostra zmienność","pt":"Volatilidade acentuada","ro":"Volatilitate ridicată","ru":"Резкая волатильность","sv":"Skarp volatilitet","th":"ความผันผวนรุนแรง","tr":"Keskin Volatilite","uk":"Різка волатильність","ur":"شدید اتار چڑھاؤ","vi":"Biến động mạnh","zh":"剧烈波动"},
    "Sideways Volatility": {"ar":"تقلب جانبي","bn":"পার্শ্বীয় অস্থিরতা","cs":"Postranní volatilita","da":"Sideways volatilitet","de":"Seitwärtsvolatilität","es":"Volatilidad lateral","fa":"نوسان جانبی","fi":"Sivusuuntainen volatiliteetti","fil":"Sideways Volatility","fr":"Volatilité latérale","he":"תנודתיות צידית","hi":"साइडवे अस्थिरता","hu":"Oldalirányú volatilitás","id":"Volatilitas Sideways","it":"Volatilità laterale","ja":"レンジボラティリティ","ko":"횡보 변동성","ms":"Volatiliti Sideways","nl":"Zijwaartse volatiliteit","no":"Sideways volatilitet","pl":"Boczna zmienność","pt":"Volatilidade lateral","ro":"Volatilitate laterală","ru":"Боковая волатильность","sv":"Sideways volatilitet","th":"ความผันผวนไร้ทิศทาง","tr":"Yatay Volatilite","uk":"Бічна волатильність","ur":"سمتی اتار چڑھاؤ","vi":"Biến động ngang","zh":"横盘波动"},
    "Risk Assessment": {"ar":"تقييم المخاطر","bn":"ঝুঁকি মূল্যায়ন","cs":"Hodnocení rizik","da":"Risikovurdering","de":"Risikobewertung","es":"Evaluación de riesgos","fa":"ارزیابی ریسک","fi":"Riskinarviointi","fil":"Pagsusuri sa Panganib","fr":"Évaluation des risques","he":"הערכת סיכונים","hi":"जोखिम मूल्यांकन","hu":"Kockázatértékelés","id":"Penilaian Risiko","it":"Valutazione dei rischi","ja":"リスク評価","ko":"위험 평가","ms":"Penilaian Risiko","nl":"Risicobeoordeling","no":"Risikovurdering","pl":"Ocena ryzyka","pt":"Avaliação de risco","ro":"Evaluare riscuri","ru":"Оценка рисков","sv":"Riskbedömning","th":"การประเมินความเสี่ยง","tr":"Risk Değerlendirmesi","uk":"Оцінка ризиків","ur":"خطرے کا جائزہ","vi":"Đánh giá rủi ro","zh":"风险评估"},
    "Risk Level": {"ar":"مستوى المخاطرة","bn":"ঝুঁকির মাত্রা","cs":"Úroveň rizika","da":"Risikoniveau","de":"Risikolevel","es":"Nivel de riesgo","fa":"سطح ریسک","fi":"Riskitaso","fil":"Antas ng Panganib","fr":"Niveau de risque","he":"רמת סיכון","hi":"जोखिम स्तर","hu":"Kockázati szint","id":"Tingkat Risiko","it":"Livello di rischio","ja":"リスクレベル","ko":"위험 수준","ms":"Tahap Risiko","nl":"Risiconiveau","no":"Risikonivå","pl":"Poziom ryzyka","pt":"Nível de risco","ro":"Nivel de risc","ru":"Уровень риска","sv":"Risknivå","th":"ระดับความเสี่ยง","tr":"Risk Seviyesi","uk":"Рівень ризику","ur":"خطرے کی سطح","vi":"Mức rủi ro","zh":"风险等级"},
    "Overall Trend": {"ar":"الاتجاه العام","bn":"সামগ্রিক ট্রেন্ড","cs":"Celkový trend","da":"Overordnet tendens","de":"Gesamttrend","es":"Tendencia general","fa":"روند کلی","fi":"Yleinen trendi","fil":"Pangkalahatang Trend","fr":"Tendance générale","he":"מגמה כללית","hi":"समग्र ट्रेंड","hu":"Általános trend","id":"Tren Keseluruhan","it":"Trend generale","ja":"全体的なトレンド","ko":"전체 추세","ms":"Trend Keseluruhan","nl":"Algemene trend","no":"Overordnet trend","pl":"Ogólny trend","pt":"Tendência geral","ro":"Trend general","ru":"Общий тренд","sv":"Övergripande trend","th":"แนวโน้มโดยรวม","tr":"Genel Trend","uk":"Загальний тренд","ur":"مجموعی رجحان","vi":"Xu hướng chung","zh":"总体趋势"},
    "Analysis Steps": {"ar":"خطوات التحليل","bn":"বিশ্লেষণের ধাপ","cs":"Kroky analýzy","da":"Analysetrinn","de":"Analyseschritte","es":"Pasos de análisis","fa":"مراحل تحلیل","fi":"Analyysivaiheet","fil":"Mga Hakbang sa Pagsusuri","fr":"Étapes d'analyse","he":"שלבי ניתוח","hi":"विश्लेषण चरण","hu":"Elemzési lépések","id":"Langkah Analisis","it":"Passaggi di analisi","ja":"分析ステップ","ko":"분석 단계","ms":"Langkah Analisis","nl":"Analysestappen","no":"Analysetrinn","pl":"Kroki analizy","pt":"Etapas de análise","ro":"Pași de analiză","ru":"Шаги анализа","sv":"Analyssteg","th":"ขั้นตอนการวิเคราะห์","tr":"Analiz Adımları","uk":"Кроки аналізу","ur":"تجزیہ کے مراحل","vi":"Các bước phân tích","zh":"分析步骤"},
    "Strategic Council Signals": {"ar":"إشارات المجلس الاستراتيجي","bn":"স্ট্র্যাটেজিক কাউন্সিল সিগন্যাল","cs":"Signály strategické rady","da":"Strategiske råds signaler","de":"Strategierat-Signale","es":"Señales del Consejo Estratégico","fa":"سیگنال‌های شورای استراتژیک","fi":"Strategisen neuvoston signaalit","fil":"Mga Signal ng Strategic Council","fr":"Signaux du conseil stratégique","he":"אותות מועצה אסטרטגית","hi":"सामरिक परिषद संकेत","hu":"Stratégiai tanács jelei","id":"Sinyal Dewan Strategis","it":"Segnali del consiglio strategico","ja":"戦略会議シグナル","ko":"전략 위원회 시그널","ms":"Isyarat Majlis Strategik","nl":"Strategische raad signalen","no":"Strategisk råd-signaler","pl":"Sygnały Rady Strategicznej","pt":"Sinais do Conselho Estratégico","ro":"Semnale Consiliu Strategic","ru":"Сигналы Стратегического Совета","sv":"Strategiråd-signaler","th":"สัญญาณจากสภายุทธศาสตร์","tr":"Stratejik Konsey Sinyalleri","uk":"Сигнали Стратегічної Ради","ur":"اسٹریٹجک کونسل سگنلز","vi":"Tín hiệu Hội đồng Chiến lược","zh":"战略委员会信号"},
    "Digital Confidence Index": {"ar":"مؤشر الثقة الرقمية","bn":"ডিজিটাল কনফিডেন্স ইনডেক্স","cs":"Index digitální důvěry","da":"Digital tillidsindeks","de":"Digitaler Vertrauensindex","es":"Índice de Confianza Digital","fa":"شاخص اعتماد دیجیتال","fi":"Digitaalinen luottamusindeksi","fil":"Digital Confidence Index","fr":"Indice de confiance numérique","he":"מדד אמון דיגיטלי","hi":"डिजिटल विश्वास सूचकांक","hu":"Digitális bizalom index","id":"Indeks Kepercayaan Digital","it":"Indice di fiducia digitale","ja":"デジタル信頼指数","ko":"디지털 신뢰 지수","ms":"Indeks Keyakinan Digital","nl":"Digitaal vertrouwensindex","no":"Digital tillitsindeks","pl":"Cyfrowy indeks zaufania","pt":"Índice de Confiança Digital","ro":"Indice de încredere digitală","ru":"Индекс цифровой уверенности","sv":"Digitalt förtroendeindex","th":"ดัชนีความมั่นใจดิจิทัล","tr":"Dijital Güven Endeksi","uk":"Індекс цифрової довіри","ur":"ڈیجیٹل اعتماد انڈیکس","vi":"Chỉ số tin cậy kỹ thuật số","zh":"数字信心指数"},
    "Global News Analysis": {"ar":"تحليل الأخبار العالمية","bn":"বৈশ্বিক সংবাদ বিশ্লেষণ","cs":"Analýza globálních zpráv","da":"Global nyhedsanalyse","de":"Globale Nachrichtenanalyse","es":"Análisis de noticias globales","fa":"تحلیل اخبار جهانی","fi":"Globaali uutisanalyysi","fil":"Pagsusuri sa Pandaigdigang Balita","fr":"Analyse de l'actualité mondiale","he":"ניתוח חדשות גלובלי","hi":"वैश्विक समाचार विश्लेषण","hu":"Globális hír_elemzés","id":"Analisis Berita Global","it":"Analisi notizie globali","ja":"グローバルニュース分析","ko":"글로벌 뉴스 분석","ms":"Analisis Berita Global","nl":"Wereldwijd nieuwsanalyse","no":"Global nyhetsanalyse","pl":"Analiza globalnych wiadomości","pt":"Análise de notícias globais","ro":"Analiză știri globale","ru":"Анализ мировых новостей","sv":"Global nyhetsanalys","th":"วิเคราะห์ข่าวโลก","tr":"Küresel Haber Analizi","uk":"Аналіз світових новин","ur":"عالمی خبروں کا تجزیہ","vi":"Phân tích tin tức toàn cầu","zh":"全球新闻分析"},
    "Smart Recommendation": {"ar":"توصية ذكية","bn":"স্মার্ট সুপারিশ","cs":"Chytré doporučení","da":"Smart anbefaling","de":"Smarte Empfehlung","es":"Recomendación inteligente","fa":"توصیه هوشمند","fi":"Älykäs suositus","fil":"Smart na Rekomendasyon","fr":"Recommandation intelligente","he":"המלצה חכמה","hi":"स्मार्ट सिफारिश","hu":"Okos ajánlás","id":"Rekomendasi Cerdas","it":"Raccomandazione intelligente","ja":"スマートレコメンデーション","ko":"스마트 추천","ms":"Cadangan Pintar","nl":"Slimme aanbeveling","no":"Smart anbefaling","pl":"Inteligentna rekomendacja","pt":"Recomendação inteligente","ro":"Recomandare inteligentă","ru":"Умная рекомендация","sv":"Smart rekommendation","th":"คำแนะนำอัจฉริยะ","tr":"Akıllı Öneri","uk":"Розумна рекомендація","ur":"سمارٹ تجاویز","vi":"Đề xuất thông minh","zh":"智能推荐"},
    "Sovereign Bearish": {"ar":"هابط سيادي","bn":"সার্বভৌম বিয়ারিশ","cs":"Suverénní medvědí","da":"Suveræn bearish","de":"Souverän bärisch","es":"Bajista soberano","fa":"نزولی حاکمیتی","fi":"Suvereeni laskava","fil":"Sovereign Bearish","fr":"Baissier souverain","he":"ריבוני דובי","hi":"संप्रभु मंदी","hu":"Szuverén medve","id":"Bearish Berdaulat","it":"Ribassista sovrano","ja":"ソブリン・ベアリッシュ","ko":"주도 약세","ms":"Bearish Berdaulat","nl":"Soevereine bearish","no":"Suveræn bearish","pl":"Suwerenny spadkowy","pt":"Baixista soberano","ro":"Bearish suveran","ru":"Суверенный медвежий","sv":"Suverän bearish","th":"ขาลงระดับหลัก","tr":"Sovereign Düşüş","uk":"Суверенний ведмежий","ur":"ذاتی بیئرش","vi":"Giảm chủ đạo","zh":"主权看跌"},
    "Very Low": {"ar":"منخفض جداً","bn":"খুব কম","cs":"Velmi nízký","da":"Meget lav","de":"Sehr niedrig","es":"Muy bajo","fa":"بسیار پایین","fi":"Erittäin matala","fil":"Napakababa","fr":"Très bas","he":"נמוך מאוד","hi":"बहुत कम","hu":"Nagyon alacsony","id":"Sangat Rendah","it":"Molto basso","ja":"非常に低い","ko":"매우 낮음","ms":"Sangat Rendah","nl":"Zeer laag","no":"Svært lav","pl":"Bardzo niski","pt":"Muito baixo","ro":"Foarte scăzut","ru":"Очень низкий","sv":"Mycket låg","th":"ต่ำมาก","tr":"Çok Düşük","uk":"Дуже низький","ur":"بہت کم","vi":"Rất thấp","zh":"极低"},
    "What's happening in {symbol}?": {"ar":"ماذا يحدث في {symbol}؟","bn":"{symbol} এ কী হচ্ছে?","cs":"Co se děje v {symbol}?","da":"Hvad sker der i {symbol}?","de":"Was passiert bei {symbol}?","es":"¿Qué está pasando en {symbol}?","fa":"در {symbol} چه اتفاقی می‌افتد؟","fi":"Mitä tapahtuu {symbol}ssa?","fil":"Anong nangyayari sa {symbol}?","fr":"Que se passe-t-il sur {symbol} ?","he":"מה קורה ב-{symbol}?","hi":"{symbol} में क्या हो रहा है?","hu":"Mi történik a {symbol}-ban?","id":"Apa yang terjadi di {symbol}?","it":"Cosa sta succedendo su {symbol}?","ja":"{symbol}で何が起きていますか？","ko":"{symbol}에서 무슨 일이 일어나고 있나요?","ms":"Apa yang berlaku di {symbol}?","nl":"Wat gebeurt er in {symbol}?","no":"Hva skjer i {symbol}?","pl":"Co się dzieje z {symbol}?","pt":"O que está acontecendo com {symbol}?","ro":"Ce se întâmplă cu {symbol}?","ru":"Что происходит с {symbol}?","sv":"Vad händer med {symbol}?","th":"เกิดอะไรขึ้นกับ {symbol}?","tr":"{symbol}'de neler oluyor?","uk":"Що відбувається з {symbol}?","ur":"{symbol} میں کیا ہو رہا ہے؟","vi":"Điều gì đang xảy ra với {symbol}?","zh":"{symbol}正在发生什么？"},
}

# Missing keys (same 9 keys for all non-Arabic languages)
MISSING_KEYS = {
    "dashboard.settings.noActiveSessions": {"ar":"لا توجد جلسات نشطة","bn":"কোনো সক্রিয় সেশন নেই","cs":"Žádné aktivní relace","da":"Ingen aktive sessioner","de":"Keine aktiven Sitzungen","es":"No hay sesiones activas","fa":"هیچ نشست فعالی وجود ندارد","fi":"Ei aktiivisia istuntoja","fil":"Walang aktibong sesyon","fr":"Aucune session active","he":"אין הפעלות פעילות","hi":"कोई सक्रिय सेशन नहीं","hu":"Nincs aktív munkamenet","id":"Tidak ada sesi aktif","it":"Nessuna sessione attiva","ja":"アクティブなセッションはありません","ko":"활성 세션 없음","ms":"Tiada sesi aktif","nl":"Geen actieve sessies","no":"Ingen aktive økter","pl":"Brak aktywnych sesji","pt":"Nenhuma sessão ativa","ro":"Nicio sesiune activă","ru":"Нет активных сессий","sv":"Inga aktiva sessioner","th":"ไม่มีเซสชันที่ใช้งานอยู่","tr":"Aktif oturum yok","uk":"Немає активних сесій","ur":"کوئی فعال سیشن نہیں","vi":"Không có phiên hoạt động","zh":"无活跃会话"},
    "dashboard.settings.unknownDevice": {"ar":"جهاز غير معروف","bn":"অজানা ডিভাইস","cs":"Neznámé zařízení","da":"Ukendt enhed","de":"Unbekanntes Gerät","es":"Dispositivo desconocido","fa":"دستگاه ناشناخته","fi":"Tuntematon laite","fil":"Hindi kilalang device","fr":"Appareil inconnu","he":"מכשיר לא ידוע","hi":"अज्ञात डिवाइस","hu":"Ismeretlen eszköz","id":"Perangkat tidak dikenal","it":"Dispositivo sconosciuto","ja":"不明なデバイス","ko":"알 수 없는 기기","ms":"Peranti Tidak Dikenali","nl":"Onbekend apparaat","no":"Ukjent enhet","pl":"Nieznane urządzenie","pt":"Dispositivo desconhecido","ro":"Dispozitiv necunoscut","ru":"Неизвестное устройство","sv":"Okänd enhet","th":"อุปกรณ์ที่ไม่รู้จัก","tr":"Bilinmeyen cihaz","uk":"Невідомий пристрій","ur":"نامعلوم ڈیوائس","vi":"Thiết bị không xác định","zh":"未知设备"},
    "dashboard.trading.balanceTooltipPaper": {"ar":"رصيدك الفعلي — يشمل الهامش المقفل في الصفقات المفتوحة","bn":"আপনার প্রকৃত ব্যালেন্স — খোলা পজিশনে লক করা মার্জিন সহ","cs":"Váš skutečný zůstatek — zahrnuje margin uzamčený v otevřených pozicích","da":"Din faktiske saldo — inkluderer margin låst i åbne positioner","de":"Ihr tatsächliches Guthaben — einschließlich in offenen Positionen gebundener Margin","es":"Su saldo real — incluye el margen bloqueado en posiciones abiertas","fa":"موجودی واقعی شما — شامل مارجین قفل شده در پوزیشن‌های باز","fi":"Todellinen saldosi — sisältää avoimiin positioihin lukitun marginaalin","fil":"Ang iyong aktwal na balanse — kasama ang margin na nakalock sa open positions","fr":"Votre solde réel — inclut la marge bloquée dans les positions ouvertes","he":"היתרה בפועל שלך — כוללת מרג'ין חסום בפוזיציות פתוחות","hi":"आपका वास्तविक बैलेंस — खुली पोजीशन में लॉक मार्जिन शामिल","hu":"Tényleges egyenlege — tartalmazza a nyitott pozíciókban lekötött margint","id":"Saldo aktual Anda — termasuk margin yang terkunci di posisi terbuka","it":"Il tuo saldo reale — include il margine bloccato nelle posizioni aperte","ja":"実際の残高 — 未決済ポジションでロックされた証拠金を含む","ko":"실제 잔고 — 미결제 포지션에 묶인 증거금 포함","ms":"Baki sebenar anda — termasuk margin yang dikunci dalam posisi terbuka","nl":"Uw werkelijke saldo — inclusief margin vastgezet in open posities","no":"Din faktiske saldo — inkluderer margin låst i åpne posisjoner","pl":"Twoje rzeczywiste saldo — obejmuje margines zablokowany w otwartych pozycjach","pt":"Seu saldo real — inclui margem travada em posições abertas","ro":"Soldul dumneavoastră real — include marja blocată în pozițiile deschise","ru":"Ваш фактический баланс — включает маржу, заблокированную в открытых позициях","sv":"Ditt faktiska saldo — inkluderar marginal låst i öppna positioner","th":"ยอดคงเหลือจริงของคุณ — รวมมาร์จินที่ล็อกในพอซิชันที่เปิดอยู่","tr":"Gerçek bakiyeniz — açık pozisyonlarda kilitli teminat dahil","uk":"Ваш фактичний баланс — включає маржу, заблоковану у відкритих позиціях","ur":"آپ کا اصل بیلنس — کھلی پوزیشنز میں لاک مارجن شامل","vi":"Số dư thực tế của bạn — bao gồm ký quỹ bị khóa trong các vị thế mở","zh":"您的实际余额 — 包括在未平仓头寸中锁定的保证金"},
    "dashboard.trading.balanceTooltipReal": {"ar":"إجمالي رصيد المحفظة — يشمل الهامش المستخدم في الصفقات","bn":"মোট ওয়ালেট ব্যালেন্স — পজিশনে ব্যবহৃত মার্জিন সহ","cs":"Celkový zůstatek peněženky — zahrnuje margin použitý v pozicích","da":"Total tegnebogssaldo — inkluderer margin brugt i positioner","de":"Gesamtes Wallet-Guthaben — einschließlich in Positionen verwendeter Margin","es":"Saldo total de la billetera — incluye el margen utilizado en posiciones","fa":"موجودی کل کیف پول — شامل مارجین استفاده شده در پوزیشن‌ها","fi":"Kokonaissaldo — sisältää positioissa käytetyn marginaalin","fil":"Kabuuang balanse ng wallet — kasama ang margin na ginamit sa mga posisyon","fr":"Solde total du portefeuille — inclut la marge utilisée dans les positions","he":"יתרת ארנק כוללת — כוללת מרג'ין בשימוש בפוזיציות","hi":"कुल वॉलेट बैलेंस — पोजीशन में उपयोग मार्जिन शामिल","hu":"Teljes pénztárca egyenleg — tartalmazza a pozíciókban felhasznált margint","id":"Total saldo dompet — termasuk margin yang digunakan dalam posisi","it":"Saldo totale del portafoglio — include il margine utilizzato nelle posizioni","ja":"ウォレット残高合計 — ポジションで使用中の証拠金を含む","ko":"총 지갑 잔고 — 포지션에 사용된 증거금 포함","ms":"Jumlah baki dompet — termasuk margin yang digunakan dalam posisi","nl":"Totale walletsaldo — inclusief margin gebruikt in posities","no":"Total lommeboksaldo — inkluderer margin brukt i posisjoner","pl":"Całkowite saldo portfela — obejmuje margines użyty w pozycjach","pt":"Saldo total da carteira — inclui margem usada em posições","ro":"Soldul total al portofelului — include marja utilizată în poziții","ru":"Общий баланс кошелька — включает маржу, используемую в позициях","sv":"Totalt plånbokssaldo — inkluderar marginal använd i positioner","th":"ยอดคงเหลือกระเป๋าทั้งหมด — รวมมาร์จินที่ใช้ในพอซิชัน","tr":"Toplam cüzdan bakiyesi — pozisyonlarda kullanılan teminat dahil","uk":"Загальний баланс гаманця — включає маржу, використану в позиціях","ur":"کل والیٹ بیلنس — پوزیشنز میں استعمال مارجن شامل","vi":"Tổng số dư ví — bao gồm ký quỹ được sử dụng trong các vị thế","zh":"钱包总余额 — 包括头寸中使用的保证金"},
    "dashboard.trading.equityTooltip": {"ar":"الرصيد + الأرباح/الخسائر غير المحققة — تتغير مع تحرك الأسعار","bn":"ব্যালেন্স + অবাস্তবায়িত লাভ/ক্ষতি — মূল্য পরিবর্তনের সাথে পরিবর্তিত হয়","cs":"Zůstatek + nerealizovaný P/L — mění se s pohybem cen","da":"Saldo + urealiseret P/L — ændres med prisbevægelser","de":"Guthaben + nicht realisierter P/L — ändert sich mit Preisbewegungen","es":"Saldo + P/L no realizado — cambia con los movimientos de precio","fa":"بالانس + سود/زیان محقق‌نشده — با حرکت قیمت‌ها تغییر می‌کند","fi":"Saldo + realisedoimaton P/L — muuttuu hintojen liikkeiden mukaan","fil":"Balanse + Unrealized P/L — nagbabago sa paggalaw ng presyo","fr":"Solde + P/L non réalisé — évolue avec les mouvements de prix","he":"יתרה + P/L לא ממומש — משתנה עם תנועות מחיר","hi":"बैलेंस + अवास्तविक P/L — कीमत की गति के साथ बदलता है","hu":"Egyenleg + nem realizált P/L — az árváltozásokkal módosul","id":"Saldo + P/L terealisasi — berubah seiring pergerakan harga","it":"Saldo + P/L non realizzato — cambia con i movimenti dei prezzi","ja":"残高 + 未実現P/L — 価格変動により変化","ko":"잔고 + 미실현 P/L — 가격 움직임에 따라 변동","ms":"Baki + P/L tidak direalisasi — berubah dengan pergerakan harga","nl":"Saldo + ongerealiseerde P/L — verandert met prijsbewegingen","no":"Saldo + urealisert P/L — endres med prisbevegelser","pl":"Saldo + niezrealizowany P/L — zmienia się wraz z ruchami cen","pt":"Saldo + P/L não realizado — muda com os movimentos de preço","ro":"Sold + P/L nerealizat — se modifică cu mișcările prețurilor","ru":"Баланс + нереализованный P/L — меняется с движением цен","sv":"Saldo + orealiserad P/L — ändras med prisrörelser","th":"ยอดคงเหลือ + P/L ที่ยังไม่รับรู้ — เปลี่ยนตามราคาที่เคลื่อนไหว","tr":"Bakiye + Gerçekleşmemiş P/L — fiyat hareketleriyle değişir","uk":"Баланс + нереалізований P/L — змінюється з рухом цін","ur":"بیلنس + غیر حاصل شدہ P/L — قیمت کی حرکت کے ساتھ تبدیل ہوتا ہے","vi":"Số dư + P/L chưa thực hiện — thay đổi theo biến động giá","zh":"余额 + 未实现P/L — 随价格变动而变化"},
    "dashboard.trading.freeMarginTooltip": {"ar":"المبلغ المتاح لفتح صفقات جديدة = الرصيد - الهامش المستخدم + الأرباح/الخسائر غير المحققة","bn":"নতুন পজিশন খোলার জন্য উপলব্ধ পরিমাণ = ব্যালেন্স - ব্যবহৃত মার্জিন + অবাস্তবায়িত P/L","cs":"Částka dostupná pro otevření nových pozic = Zůstatek - Použitý margin + Nerealizovaný P/L","da":"Beløb tilgængelig til nye positioner = Saldo - Brugt margin + urealiseret P/L","de":"Für neue Positionen verfügbarer Betrag = Guthaben - Verwendete Margin + Nicht realisierter P/L","es":"Monto disponible para abrir nuevas posiciones = Saldo - Margen utilizado + P/L no realizado","fa":"مبلغ قابل دسترس برای باز کردن پوزیشن جدید = بالانس - مارجین استفاده شده + سود/زیان محقق‌نشده","fi":"Uusien positioiden avaamiseen saatavilla oleva määrä = Saldo - Käytetty marginaali + Realisedoimaton P/L","fil":"Halaga na available para magbukas ng bagong posisyon = Balanse - Ginamit na Margin + Unrealized P/L","fr":"Montant disponible pour ouvrir de nouvelles positions = Solde - Marge utilisée + P/L non réalisé","he":"סכום זמין לפתיחת פוזיציות חדשות = יתרה - מרג'ין בשימוש + P/L לא ממומש","hi":"नई पोजीशन खोलने के लिए उपलब्ध राशि = बैलेंस - उपयोग मार्जिन + अवास्तविक P/L","hu":"Új pozíciók nyitására rendelkezésre álló összeg = Egyenleg - Felhasznált margin + Nem realizált P/L","id":"Jumlah tersedia untuk membuka posisi baru = Saldo - Margin Terpakai + P/L terealisasi","it":"Importo disponibile per aprire nuove posizioni = Saldo - Margine utilizzato + P/L non realizzato","ja":"新しいポジションを開くための利用可能額 = 残高 - 使用証拠金 + 未実現P/L","ko":"신규 포지션 개시 가능 금액 = 잔고 - 사용 증거금 + 미실현 P/L","ms":"Jumlah tersedia untuk membuka posisi baharu = Baki - Margin Digunakan + P/L tidak direalisasi","nl":"Bedrag beschikbaar voor nieuwe posities = Saldo - Gebruikte margin + Ongerealiseerde P/L","no":"Beløp tilgjengelig for nye posisjoner = Saldo - Brukt margin + Urealisert P/L","pl":"Kwota dostępna na otwarcie nowych pozycji = Saldo - Użyty margines + Niezrealizowany P/L","pt":"Valor disponível para abrir novas posições = Saldo - Margem usada + P/L não realizado","ro":"Sumă disponibilă pentru deschiderea de poziții noi = Sold - Marjă utilizată + P/L nerealizat","ru":"Сумма для открытия новых позиций = Баланс - Использованная маржа + Нереализованный P/L","sv":"Belopp tillgängligt för nya positioner = Saldo - Använd marginal + Orealiserad P/L","th":"จำนวนที่ใช้เปิดพอซิชันใหม่ได้ = ยอดคงเหลือ - มาร์จินที่ใช้ + P/L ที่ยังไม่รับรู้","tr":"Yeni pozisyon açmak için kullanılabilir tutar = Bakiye - Kullanılan Teminat + Gerçekleşmemiş P/L","uk":"Сума для відкриття нових позицій = Баланс - Використана маржа + Нереалізований P/L","ur":"نئی پوزیشن کھولنے کے لیے دستیاب رقم = بیلنس - استعمال مارجن + غیر حاصل شدہ P/L","vi":"Số tiền khả dụng để mở vị thế mới = Số dư - Ký quỹ đã dùng + P/L chưa thực hiện","zh":"可用于开新仓的金额 = 余额 - 已用保证金 + 未实现P/L"},
    "dashboard.trading.usedMarginTooltip": {"ar":"المبلغ المقفل كضمان للصفقات المفتوحة — يُسترد عند الإغلاق","bn":"খোলা পজিশনের জন্য কোল্যাটারাল হিসেবে লক করা পরিমাণ — বন্ধ করলে ফেরত পাওয়া যায়","cs":"Částka uzamčená jako zástava pro otevřené pozice — vrácena při uzavření","da":"Beløb låst som sikkerhed for åbne positioner — returneres ved lukning","de":"Als Sicherheit für offene Positionen geblockter Betrag — wird bei Schließung zurückgegeben","es":"Monto bloqueado como garantía de posiciones abiertas — se devuelve al cerrar","fa":"مبلغ قفل شده به عنوان وثیقه برای پوزیشن‌های باز — هنگام بستن برگردانده می‌شود","fi":"Avoimien positioiden vakuudeksi lukittu määrä — palautetaan suljettaessa","fil":"Halagang nakalock bilang collateral para sa open positions — ibinalik sa pagsasara","fr":"Montant bloqué en garantie pour les positions ouvertes — restitué à la clôture","he":"סכום חסום כערבות לפוזיציות פתוחות — מוחזר בסגירה","hi":"खुली पोजीशन के लिए कॉलेटरल के रूप में लॉक राशि — बंद करने पर वापस मिलती है","hu":"Nyitott pozíciók fedezeteként lekötött összeg — záráskor visszatérítve","id":"Jumlah yang dikunci sebagai jaminan untuk posisi terbuka — dikembalikan saat ditutup","it":"Importo bloccato come garanzia per le posizioni aperte — reso alla chiusura","ja":"未決済ポジションの担保としてロックされた金額 — 決済時に返還","ko":"미결제 포지션의 담보로 잠긴 금액 — 청산 시 반환","ms":"Jumlah dikunci sebagai cagaran untuk posisi terbuka — dikembalikan semasa penutupan","nl":"Als onderpand voor open posities geblokkeerd bedrag — wordt teruggegeven bij sluiting","no":"Beløp låst som sikkerhet for åpne posisjoner — returneres ved stenget","pl":"Kwota zablokowana jako zabezpieczenie otwartych pozycji — zwracana przy zamknięciu","pt":"Valor bloqueado como garantia de posições abertas — devolvido ao fechar","ro":"Sumă blocată drept garanție pentru pozițiile deschise — returnată la închidere","ru":"Сумма, заблокированная как обеспечение открытых позиций — возвращается при закрытии","sv":"Belopp låst som säkerhet för öppna positioner — återbetalas vid stängning","th":"จำนวนที่ล็อกเป็นหลักประกันสำหรับพอซิชันที่เปิดอยู่ — คืนเมื่อปิด","tr":"Açık pozisyonlar için teminat olarak kilitli tutar — kapanışta iade edilir","uk":"Сума, заблокована як забезпечення відкритих позицій — повертається при закритті","ur":"کھلی پوزیشنز کے لیے ضمانت کے طور پر لاک رقم — بند کرنے پر واپس ملتی ہے","vi":"Số tiền bị khóa làm tài sản đảm bảo cho các vị thế mở — được hoàn trả khi đóng","zh":"作为未平仓头寸担保而锁定的金额 — 平仓时退还"},
    "portfolio.balance": {"ar":"الرصيد","bn":"ব্যালেন্স","cs":"Zůstatek","da":"Saldo","de":"Guthaben","es":"Saldo","fa":"موجودی","fi":"Saldo","fil":"Balanse","fr":"Solde","he":"יתרה","hi":"बैलेंस","hu":"Egyenleg","id":"Saldo","it":"Saldo","ja":"残高","ko":"잔고","ms":"Baki","nl":"Saldo","no":"Saldo","pl":"Saldo","pt":"Saldo","ro":"Sold","ru":"Баланс","sv":"Saldo","th":"ยอดคงเหลือ","tr":"Bakiye","uk":"Баланс","ur":"بیلنس","vi":"Số dư","zh":"余额"},
    "portfolio.freeMargin": {"ar":"الهامش المتاح","bn":"ফ্রি মার্জিন","cs":"Volný margin","da":"Fri margin","de":"Freie Margin","es":"Margen libre","fa":"مارجین آزاد","fi":"Vapaa marginaali","fil":"Free Margin","fr":"Marge libre","he":"מרג'ין פנוי","hi":"फ्री मार्जिन","hu":"Szabad margin","id":"Margin Bebas","it":"Margine libero","ja":"余剰証拠金","ko":"사용 가능 증거금","ms":"Margin Bebas","nl":"Vrije margin","no":"Fri margin","pl":"Wolny margines","pt":"Margem livre","ro":"Marjă liberă","ru":"Свободная маржа","sv":"Fri marginal","th":"มาร์จินว่าง","tr":"Serbest Teminat","uk":"Вільна маржа","ur":"فری مارجن","vi":"Ký quỹ tự do","zh":"可用保证金"},
}

def fix_all_translations():
    en = load_json('en')
    
    # Get all language codes
    lang_files = [f for f in os.listdir(MESSAGES_DIR) if f.endswith('.json') and f != 'en.json']
    lang_codes = sorted([f.replace('.json', '') for f in lang_files])
    
    stats = {}
    
    for lang in lang_codes:
        data = load_json(lang)
        changes = 0
        
        # 1. Add missing keys
        for key_path, translations in MISSING_KEYS.items():
            if lang in translations:
                if not has_key(data, key_path):
                    set_value(data, key_path, translations[lang])
                    changes += 1
        
        # 2. Translate untranslated values (same as English)
        def fix_untranslated(en_obj, lang_obj, prefix=''):
            nonlocal changes
            for k, v in en_obj.items():
                full_key = f'{prefix}.{k}' if prefix else k
                if isinstance(v, dict):
                    if k in lang_obj and isinstance(lang_obj[k], dict):
                        fix_untranslated(v, lang_obj[k], full_key)
                    # If whole section missing, don't handle here (would need deep merge)
                else:
                    if k in lang_obj and lang_obj[k] == v and v:
                        # Check if we have a translation
                        if v in COMMON:
                            if lang in COMMON[v]:
                                lang_obj[k] = COMMON[v][lang]
                                changes += 1
                        # Check if key is in MISSING_KEYS (already handled above)
        
        fix_untranslated(en, data)
        
        # Save
        save_json(lang, data)
        stats[lang] = changes
    
    # Print stats
    print("Translation fix results:")
    for lang, changes in sorted(stats.items(), key=lambda x: -x[1]):
        print(f"  {lang}: {changes} fixes")
    
    # Count remaining
    print("\nRemaining untranslated keys:")
    for lang in lang_codes:
        data = load_json(lang)
        count = 0
        def count_same(en_obj, lang_obj, prefix=''):
            nonlocal count
            for k, v in en_obj.items():
                full_key = f'{prefix}.{k}' if prefix else k
                if isinstance(v, dict):
                    if k in lang_obj and isinstance(lang_obj[k], dict):
                        count_same(v, lang_obj[k], full_key)
                else:
                    if k in lang_obj and lang_obj[k] == v and v:
                        count += 1
        count_same(en, data)
        if count > 0:
            print(f"  {lang}: {count}")

if __name__ == '__main__':
    fix_all_translations()
